nameOverride: ""
fullnameOverride: ""

kind: "StatefulSet"

# IMPORTANT: specificăm clar variant opensearch
variant: opensearch

extraFilesConfigMapNameOverride: ""
mainConfigMapNameOverride: ""

image:
  repository: "fluent/fluentd-kubernetes-daemonset"
  tag: "v1.16-debian-opensearch-1"
  pullPolicy: "IfNotPresent"

serviceAccount:
  create: true
  annotations: {}
  name: null

rbac:
  create: true

podSecurityPolicy:
  enabled: false

env:
  - name: FLUENT_OPENSEARCH_HOST
    value: "opensearch-cluster-master"
  - name: FLUENT_OPENSEARCH_PORT
    value: "9200"
  - name: FLUENT_OPENSEARCH_SCHEME
    value: "http"
  - name: FLUENT_OPENSEARCH_SSL_VERIFY
    value: "false"
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

service:
  enabled: true
  type: "ClusterIP"
  ports:
    - name: "forwarder"
      protocol: TCP
      containerPort: 24224
      port: 24224

extraVolumes:
  - name: fluentd-config
    configMap:
      name: fluentd-config

extraVolumeMounts:
  - name: fluentd-config
    mountPath: /fluentd/etc/opensearch_template.json
    subPath: configmap-template-custom-ghosty.yaml

plugins:
  - fluent-plugin-opensearch

fileConfigs:
  01_sources.conf: |-
    ## Input de la fluent-bit
    <source>
      @type forward
      @id forward_input
      @label @FLUENT_BIT
      port 24224
      bind 0.0.0.0
    </source>

    ## Tail pentru loguri de containere
    <source>
      @type tail
      @id in_tail_container_logs
      @label @KUBERNETES
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_type string
          time_format "%Y-%m-%dT%H:%M:%S.%NZ"
        </pattern>
        <pattern>
          format regexp
          expression /^(?<time>.+) (?<stream>stdout|stderr)( (.))? (?<log>.*)$/
          time_format '%Y-%m-%dT%H:%M:%S.%NZ'
        </pattern>
      </parse>
    </source>

    # Endpoint Prometheus pentru metrici
    <source>
      @type prometheus
      bind 0.0.0.0
      port 24231
      metrics_path /metrics
    </source>

  02_filters.conf: |-
    <label @FLUENT_BIT>
      <match **>
        @type relabel
        @label @DISPATCH
      </match>
    </label>

    <label @KUBERNETES>
      <filter kubernetes.**>
        @type kubernetes_metadata
        @id filter_kube_metadata
        skip_labels false
        skip_container_metadata false
        skip_namespace_metadata true
        skip_master_url true
      </filter>

      <match **>
        @type relabel
        @label @DISPATCH
      </match>
    </label>

  03_dispatch.conf: |-
    <label @DISPATCH>
      <filter **>
        @type prometheus
        <metric>
          name fluentd_input_status_num_records_total
          type counter
          desc The total number of incoming records
          <labels>
            tag ${tag}
            hostname ${hostname}
          </labels>
        </metric>
      </filter>

      <match **>
        @type relabel
        @label @OUTPUT
      </match>
    </label>

  04_outputs.conf: |-
    <label @OUTPUT>
      <match **>
        @type opensearch
        @id out_opensearch
        host "opensearch-cluster-master"
        port 9200
        scheme https
        ssl_verify false
        user admin
        password "admin"
        logstash_format true
        include_tag_key true
        tag_key "@log_name"
        reconnect_on_error true
        reload_connections false
        log_es_400_reason true
        index_name "fluentd-${tag}"
        type_name _doc
        template_name "fluentd"
        template_file "/fluentd/etc/opensearch_template.json"
        template_overwrite true
        <buffer>
          @type file
          path "/fluentd/buffer"
          flush_mode interval
          flush_interval 5s
          chunk_limit_size 1M
          queue_limit_length 32
          retry_forever true
        </buffer>
      </match>

      <match **>
        @type stdout
        @id out_stdout
      </match>
    </label>
