# Image configuration
image:
  registry: docker.io
  repository: traefik
  tag: "" # uses appVersion from Chart
  pullPolicy: IfNotPresent

# Deployment configuration
deployment:
  enabled: true
  kind: Deployment
  replicas: 1

# IngressClass configuration
ingressClass:
  enabled: true
  isDefaultClass: true

# Providers configuration
providers:
  kubernetesCRD:
    enabled: true
    allowEmptyServices: true

  kubernetesIngress:
    enabled: true
    allowEmptyServices: true
    publishedService:
      enabled: true

# Ports configuration
ports:
  traefik:
    port: 8080
    expose:
      default: false

  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80

  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    tls:
      enabled: true

# Service configuration
service:
  enabled: true
  type: LoadBalancer

# Logs configuration
logs:
  general:
    level: INFO

# Security configuration
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

podSecurityContext:
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

# RBAC
rbac:
  enabled: true
