replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: nginx-test.ggdevs.site
      paths:
        - path: /
          pathType: Prefix
  tls: []
