# Kube Prometheus Stack - Production-Ready Minimal Configuration

# Prometheus Operator Configuration
prometheusOperator:
  # Disable admission webhooks to avoid image pull issues
  admissionWebhooks:
    enabled: false

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# Prometheus Configuration
prometheus:
  prometheusSpec:
    # Retention period for metrics
    retention: 15d
    retentionSize: "9GB"

    # Storage configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

    # Resource limits
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi

    # Service monitors - what to scrape
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

    # Enable persistent storage
    enableAdminAPI: true

# Alertmanager Configuration
alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

# Grafana Configuration
grafana:
  enabled: true

  # Admin credentials (CHANGE IN PRODUCTION!)
  adminPassword: "admin123"

  # Persistence
  persistence:
    enabled: true
    size: 5Gi

  # Resources
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Grafana datasources
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-stack-kube-prom-prometheus:9090
          access: proxy
          isDefault: true

  # Default dashboards
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: "Europe/Bucharest"

# Node Exporter - collects node metrics
nodeExporter:
  enabled: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# Kube State Metrics - Kubernetes cluster state
kubeStateMetrics:
  enabled: true

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Service Monitors for Kubernetes components
kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeControllerManager:
  enabled: true

coreDns:
  enabled: true

kubeEtcd:
  enabled: false # Enable if you have access to etcd

kubeScheduler:
  enabled: true

kubeProxy:
  enabled: true
