# Global settings pentru timeout-uri
global:
  imagePullPolicy: IfNotPresent

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
    createSecretJob:
      enabled: false

  tlsProxy:
    enabled: false

  tls:
    enabled: false

  serviceMonitor:
    selfMonitor: false

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  image:
    pullPolicy: IfNotPresent

# Prometheus Configuration
prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: "9GB"

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    enableAdminAPI: true

  image:
    pullPolicy: IfNotPresent

# Alertmanager Configuration
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  image:
    pullPolicy: IfNotPresent

# Grafana Configuration
grafana:
  enabled: true
  adminPassword: "admin123"

  persistence:
    enabled: true
    size: 5Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  image:
    pullPolicy: IfNotPresent

  # Timeout-uri mai mari pentru download
  downloadDashboardsImage:
    pullPolicy: IfNotPresent

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-stack-kube-prom-prometheus:9090
          access: proxy
          isDefault: true

  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: "Europe/Bucharest"

# Node Exporter
nodeExporter:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    pullPolicy: IfNotPresent

# Kube State Metrics
kubeStateMetrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  image:
    pullPolicy: IfNotPresent

# Service Monitors
kubeApiServer:
  enabled: true
kubelet:
  enabled: true
kubeControllerManager:
  enabled: true
coreDns:
  enabled: true
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: true
kubeProxy:
  enabled: true
