apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  destination:
    namespace: cloudflared
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:SabinGhost19/kubernetes-logging-stack.git
    path: apps/charts/cloudflared-chart/cloudflared
    targetRevision: main
    helm:
      valueFiles:
        - ../values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
