apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:SabinGhost19/kubernetes-logging-stack.git
    path: apps/charts/nginx-test-chart/nginx-test
    targetRevision: main
    helm:
      valueFiles:
        - ../values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
