# apps/grafana/values.yaml

image:
  repository: grafana/grafana
  tag: 9.0.0

admin:
  existingSecret: grafana-admin-secret
  # If not using existingSecret, you may set adminPassword, but NOT in git.

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false

resources:
  requests:
    cpu: "250m"
    memory: "384Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

nodeSelector:
  kubernetes.io/role: worker

tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
# For HA when you have multiple grafana pods and shared DB, enable headless service:
# headlessService: true
