apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-opensearch-template
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "fluentd.name" . }}
    chart: {{ include "fluentd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  opensearch_template.json: |
    {
      "index_patterns": ["logstash-*"],
      "settings": {
        "number_of_shards": 1
      },
      "mappings": {
        "properties": {
          "@timestamp": { "type": "date" },
          "log": { "type": "text" },
          "stream": { "type": "keyword" }
        }
      }
    }