apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
{{- with .Values.config }}
    tunnel: {{ .tunnel }}
    credentials-file: {{ .credentialsFile }}
{{- end }}
