clusterName: "opensearch-cluster"
nodeGroup: "master"
# Basic configuration
config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    node.name: ${HOSTNAME}
    discovery.type: single-node

    # Security - ENABLED with SSL (REQUIRED!)
    plugins.security.disabled: false

    # SSL for Transport Layer (REQUIRED when security is enabled)
    plugins.security.ssl.transport.enabled: true
    plugins.security.ssl.transport.pemcert_filepath: esnode.pem
    plugins.security.ssl.transport.pemkey_filepath: esnode-key.pem
    plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false

    # SSL for HTTP (optional but recommended)
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: esnode.pem
    plugins.security.ssl.http.pemkey_filepath: esnode-key.pem
    plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem

    # Security configurations
    plugins.security.allow_unsafe_democertificates: true
    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - CN=kirk,OU=client,O=client,L=test,C=de

    # Fluentd settings - updated for HTTPS
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
    http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization

  # Performance Analyzer configuration
  performance-analyzer.properties: |
    # Enable Performance Analyzer
    webservice-listener = org.opensearch.performanceanalyzer.net.NetServer
    rpc-port = 9650
    webservice-port = 9600

    # Metrics collection
    metrics-location = /dev/shm/performanceanalyzer/
    metrics-deletion-interval = 1
    https-enabled = false

    # Cleanup settings
    cleanup-metrics-db-files = true
    batch-metrics-retention-period-minutes = 7

    # Performance settings
    writer-queue-size = 10000

# Required environment variables
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "Admin123!@#" # Schimbă cu o parolă puternică!
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "false"
  # ACTIVEAZĂ Performance Analyzer
  - name: DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI
    value: "false"

# Correct plugins configuration
plugins:
  enabled: true
  install: ["analysis-icu"]

# Resources - increased for Performance Analyzer
resources:
  requests:
    memory: "1.5Gi"
    cpu: "750m"
  limits:
    memory: "2.5Gi"
    cpu: "1500m"

# Java Heap Size - adjusted for memory limit
opensearchJavaOpts: "-Xms512m -Xmx512m"

# Persistence
persistence:
  enabled: true
  size: "20Gi"
  storageClass: ""

# Additional volume for Performance Analyzer (shared memory)
extraVolumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 512Mi

extraVolumeMounts:
  - name: shm
    mountPath: /dev/shm

# Service - add port for Performance Analyzer
service:
  type: ClusterIP
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
    - port: 9600
      name: performance-analyzer
      protocol: TCP

# Headless service for Performance Analyzer
headlessService:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

# For external access (if needed)
ingress:
  enabled: false

# Single-node for development
replicas: 1

# Node roles - use cluster_manager instead of master
roles:
  - cluster_manager
  - ingest
  - data
  - remote_cluster_client

# Security config
securityConfig:
  enabled: true
  path: "/usr/share/opensearch/config/opensearch-security"

# Sysctls for OpenSearch
sysctlInit:
  enabled: true

# Init containers to create required directories
extraInitContainers:
  - name: setup-performance-analyzer
    image: busybox:1.36
    command:
      - sh
      - -c
      - |
        mkdir -p /dev/shm/performanceanalyzer
        chmod 777 /dev/shm/performanceanalyzer
        echo "Performance Analyzer directory created"
    volumeMounts:
      - name: shm
        mountPath: /dev/shm

# Security context to allow access to /dev/shm
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
